-- Insert daily questions for next 2 months (July 15 - September 14, 2025)

INSERT INTO public.daily_questions (question, question_type, options, featured_date, is_active) VALUES
-- July 2025
('What is one positive affirmation you tell yourself daily during your health journey?', 'open', NULL, '2025-07-15', true),
('Which of these self-care activities helps you most on difficult days?', 'poll', '["Taking a warm bath", "Listening to music", "Going for a walk", "Meditation/breathing exercises", "Calling a friend"]', '2025-07-16', true),
('Share a small victory or accomplishment from this week, no matter how minor it may seem.', 'open', NULL, '2025-07-17', true),
('What percentage of cancer cases are preventable through lifestyle changes?', 'poll', '["10-20%", "30-40%", "50-60%", "70-80%"]', '2025-07-18', true),
('Complete this affirmation: "I am stronger than..."', 'open', NULL, '2025-07-19', true),
('Which symptom should you never ignore when it comes to cancer screening?', 'poll', '["Persistent fatigue", "Unexplained weight loss", "Changes in skin moles", "All of the above"]', '2025-07-20', true),
('What is one thing you are grateful for today?', 'open', NULL, '2025-07-21', true),
('How often should women perform breast self-examinations?', 'poll', '["Weekly", "Monthly", "Every 3 months", "Twice a year"]', '2025-07-22', true),
('Describe your ideal support system. What does it look like?', 'open', NULL, '2025-07-23', true),
('Which of these foods is known to help reduce cancer risk?', 'poll', '["Processed meats", "Leafy green vegetables", "Sugary drinks", "Fried foods"]', '2025-07-24', true),
('What motivates you to keep going on your hardest days?', 'open', NULL, '2025-07-25', true),
('At what age should regular mammography screening typically begin?', 'poll', '["35", "40", "45", "50"]', '2025-07-26', true),
('Share one piece of advice you would give to someone newly diagnosed.', 'open', NULL, '2025-07-27', true),
('Which lifestyle factor has the strongest link to cancer prevention?', 'poll', '["Not smoking", "Regular exercise", "Healthy diet", "All are equally important"]', '2025-07-28', true),
('What does self-compassion mean to you?', 'open', NULL, '2025-07-29', true),
('True or False: All lumps are cancerous.', 'poll', '["True", "False"]', '2025-07-30', true),
('What is one goal you want to achieve this month?', 'open', NULL, '2025-07-31', true),

-- August 2025
('How do you practice mindfulness in your daily routine?', 'open', NULL, '2025-08-01', true),
('Which of these is a common myth about cancer?', 'poll', '["Cancer is always hereditary", "Sugar feeds cancer cells", "Cancer is contagious", "All of the above"]', '2025-08-02', true),
('Complete this sentence: "Today I choose to..."', 'open', NULL, '2025-08-03', true),
('What is the most important factor in cancer treatment success?', 'poll', '["Early detection", "Positive attitude", "Access to treatment", "Strong support system"]', '2025-08-04', true),
('What brings you peace when you feel overwhelmed?', 'open', NULL, '2025-08-05', true),
('Which of these screening tests can detect colorectal cancer early?', 'poll', '["Colonoscopy", "Blood test", "X-ray", "Ultrasound"]', '2025-08-06', true),
('Share a moment when you felt truly supported by someone.', 'open', NULL, '2025-08-07', true),
('How much sleep do adults need for optimal health and immune function?', 'poll', '["5-6 hours", "7-9 hours", "10-12 hours", "It varies by person"]', '2025-08-08', true),
('What does courage look like in your life?', 'open', NULL, '2025-08-09', true),
('Which vitamin deficiency has been linked to increased cancer risk?', 'poll', '["Vitamin C", "Vitamin D", "Vitamin B12", "Vitamin A"]', '2025-08-10', true),
('Describe one way you show kindness to yourself.', 'open', NULL, '2025-08-11', true),
('What percentage of cancer survivors experience some form of fatigue?', 'poll', '["25%", "50%", "75%", "90%"]', '2025-08-12', true),
('What is something new you learned about yourself this year?', 'open', NULL, '2025-08-13', true),
('Which habit is most important for maintaining a strong immune system?', 'poll', '["Regular exercise", "Balanced nutrition", "Adequate sleep", "All are equally important"]', '2025-08-14', true),
('Share a tradition or ritual that brings you comfort.', 'open', NULL, '2025-08-15', true),
('What is the leading cause of cancer-related deaths worldwide?', 'poll', '["Breast cancer", "Lung cancer", "Colorectal cancer", "Prostate cancer"]', '2025-08-16', true),
('What does resilience mean to you?', 'open', NULL, '2025-08-17', true),
('How often should you apply sunscreen to prevent skin cancer?', 'poll', '["Once in the morning", "Every 2 hours", "Only when swimming", "Only on sunny days"]', '2025-08-18', true),
('What is one boundary you have learned to set for your wellbeing?', 'open', NULL, '2025-08-19', true),
('Which exercise has been shown to reduce cancer recurrence risk?', 'poll', '["Walking", "Swimming", "Yoga", "Any regular physical activity"]', '2025-08-20', true),
('Describe a moment when you felt proud of your strength.', 'open', NULL, '2025-08-21', true),
('What is the recommended daily intake of fruits and vegetables?', 'poll', '["3-4 servings", "5-6 servings", "7-8 servings", "9-10 servings"]', '2025-08-22', true),
('How do you celebrate small wins in your journey?', 'open', NULL, '2025-08-23', true),
('Which emotion is most commonly experienced after a cancer diagnosis?', 'poll', '["Anger", "Fear", "Sadness", "All of the above"]', '2025-08-24', true),
('What is one thing you do to nurture your mental health?', 'open', NULL, '2025-08-25', true),
('True or False: Stress directly causes cancer.', 'poll', '["True", "False"]', '2025-08-26', true),
('Share something you are looking forward to.', 'open', NULL, '2025-08-27', true),
('Which of these is a warning sign that should prompt a doctor visit?', 'poll', '["Persistent cough", "Unusual bleeding", "Unexplained pain", "All of the above"]', '2025-08-28', true),
('What does hope look like in your life today?', 'open', NULL, '2025-08-29', true),
('How long should you wait to see a doctor for a persistent symptom?', 'poll', '["1 week", "2 weeks", "1 month", "It depends on the symptom"]', '2025-08-30', true),
('Complete this affirmation: "I deserve..."', 'open', NULL, '2025-08-31', true),

-- September 2025
('What is one way you connect with others in your community?', 'open', NULL, '2025-09-01', true),
('Which factor most influences cancer treatment outcomes?', 'poll', '["Age", "Cancer stage at diagnosis", "Overall health", "Access to care"]', '2025-09-02', true),
('Share a lesson you have learned about patience.', 'open', NULL, '2025-09-03', true),
('What percentage of cancer patients experience anxiety or depression?', 'poll', '["15-25%", "30-40%", "45-55%", "60-70%"]', '2025-09-04', true),
('What gives you strength when facing uncertainty?', 'open', NULL, '2025-09-05', true),
('Which screening method is most effective for cervical cancer?', 'poll', '["Pap smear", "HPV test", "Pelvic exam", "Both Pap smear and HPV test"]', '2025-09-06', true),
('Describe one way your perspective on life has changed.', 'open', NULL, '2025-09-07', true),
('How much water should you drink daily for optimal health?', 'poll', '["4-6 glasses", "6-8 glasses", "8-10 glasses", "10-12 glasses"]', '2025-09-08', true),
('What is something you want to thank your body for today?', 'open', NULL, '2025-09-09', true),
('Which lifestyle change can reduce cancer risk by up to 30%?', 'poll', '["Quitting smoking", "Limiting alcohol", "Maintaining healthy weight", "Regular screening"]', '2025-09-10', true),
('Share one way you practice self-forgiveness.', 'open', NULL, '2025-09-11', true),
('What is the most common cancer in women worldwide?', 'poll', '["Breast cancer", "Lung cancer", "Cervical cancer", "Colorectal cancer"]', '2025-09-12', true),
('What does living fully mean to you right now?', 'open', NULL, '2025-09-13', true),
('Which of these best describes the relationship between cancer and age?', 'poll', '["Cancer only affects older adults", "Cancer risk increases with age", "Cancer affects all ages equally", "Cancer is more common in children"]', '2025-09-14', true);