// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njaeyvrtchwrdahuyhyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qYWV5dnJ0Y2h3cmRhaHV5aHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDc4NzgsImV4cCI6MjA2NTU4Mzg3OH0.2aJVzfGE97r8W6eIunafaPX_eil2W0CUbx5rmgEhlUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);